#!/usr/bin/env bash
# Snapshot a release into _local/backup/ for offline traceability.
#
# Git and GitHub Releases are already the authoritative archive: every released
# .scad is retrievable with `git show <tag>:cable-box-parametric.scad` and is
# attached to its Release. This script exists for the case those do not cover,
# which is losing access to GitHub itself.
#
# It deliberately writes to _local/ (gitignored) rather than an archive/ folder
# in the repo. Committing N copies of a 270 KB model creates ambiguity about
# which file is authoritative, and git already stores every version losslessly.
#
# Usage:
#   bash scripts/backup-release.sh            # snapshot the current HEAD state
#   bash scripts/backup-release.sh v1.2.0     # snapshot a specific tag
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

REF="${1:-HEAD}"
DEST="_local/backup"
mkdir -p "$DEST"

if [ "$REF" = "HEAD" ]; then
  LABEL="$(git rev-parse --short HEAD)-$(date +%Y%m%d)"
else
  git rev-parse -q --verify "$REF" >/dev/null 2>&1 || { echo "unknown ref: $REF"; exit 1; }
  LABEL="$REF"
fi

echo "Backing up $REF as $LABEL"

# 1. Full mirror of all refs and history. This is the real insurance.
MIRROR="$DEST/repo-mirror.git"
if [ -d "$MIRROR" ]; then
  git --git-dir="$MIRROR" remote update --prune >/dev/null 2>&1 || true
  echo "  refreshed mirror  $MIRROR"
else
  git clone --mirror . "$MIRROR" >/dev/null 2>&1
  echo "  created mirror    $MIRROR"
fi

# 2. The model file and changelog at that ref, plainly readable without git.
SNAP="$DEST/$LABEL"
mkdir -p "$SNAP"
git show "$REF:cable-box-parametric.scad" > "$SNAP/cable-box-parametric.scad" 2>/dev/null \
  || git show "$REF:cable-management-box-parametric.scad" > "$SNAP/cable-box-parametric.scad" 2>/dev/null \
  || echo "  (no model file at this ref)"
git show "$REF:CHANGELOG.md" > "$SNAP/CHANGELOG.md" 2>/dev/null || true

# 3. A manifest tying the snapshot back to its commit.
{
  echo "ref:         $REF"
  echo "commit:      $(git rev-parse "$REF")"
  echo "committed:   $(git log -1 --format=%cI "$REF")"
  echo "subject:     $(git log -1 --format=%s "$REF")"
  echo "backed_up:   $(date -Iseconds)"
  if [ -f "$SNAP/cable-box-parametric.scad" ]; then
    echo "model_sha256: $(sha256sum "$SNAP/cable-box-parametric.scad" | cut -d' ' -f1)"
    echo "model_version: $(grep -oE '^Model_Version[[:space:]]*=[[:space:]]*"[^"]+"' \
        "$SNAP/cable-box-parametric.scad" | grep -oE '"[^"]+"' | tr -d '"' || echo unknown)"
  fi
} > "$SNAP/MANIFEST.txt"

echo "  wrote snapshot    $SNAP"
sed 's/^/    /' "$SNAP/MANIFEST.txt"

# 4. Index of everything backed up so far.
{
  echo "# Release backups"
  echo
  echo "Generated by scripts/backup-release.sh. Local only, never committed."
  echo
  printf '| Snapshot | Version | Commit | Date |\n|---|---|---|---|\n'
  for d in "$DEST"/*/; do
    m="$d/MANIFEST.txt"
    [ -f "$m" ] || continue
    printf '| `%s` | %s | `%s` | %s |\n' \
      "$(basename "$d")" \
      "$(grep '^model_version:' "$m" | cut -d' ' -f2- | tr -d ' ')" \
      "$(grep '^commit:' "$m" | cut -d' ' -f2- | tr -d ' ' | cut -c1-8)" \
      "$(grep '^committed:' "$m" | cut -d' ' -f2- | tr -d ' ' | cut -c1-10)"
  done
} > "$DEST/README.md"

echo "  updated index     $DEST/README.md"
