#!/usr/bin/env python3
"""Regenerate the missing-BOSL2 test fixture from the current model.

The fixture is the model with its include pointed at a library that does not
exist, so the dependency guard can be exercised without uninstalling anything.
It has to track the model, hence a generator rather than a hand-maintained copy.
"""
import pathlib

REPO = pathlib.Path(__file__).resolve().parent.parent
src = (REPO / "cable-box-parametric.scad").read_text(encoding="utf-8", errors="surrogateescape")
out = src.replace("include <BOSL2/std.scad>", "include <BOSL2_DELIBERATELY_ABSENT/std.scad>") \
         .replace("include <BOSL2/joiners.scad>", "include <BOSL2_DELIBERATELY_ABSENT/joiners.scad>")
header = ("// Generated by scripts/regen_missing_bosl2_fixture.py. Do not edit.\n"
          "// The model with its BOSL2 include redirected to a nonexistent library,\n"
          "// so the missing-dependency guard can be tested.\n")
dest = REPO / "tests" / "fixtures" / "missing_bosl2.scad"
dest.parent.mkdir(exist_ok=True)
dest.write_text(header + out, encoding="utf-8", errors="surrogateescape")
print(f"wrote {dest.relative_to(REPO)}")
