// Copy the generated preset library into the site's public directory, so the
// browser at /library/ serves exactly the artifacts scripts/build_library.py
// produced: the same STLs people print, the same renders the README shows, and
// the GLBs the 3D viewer reads.
//
// This is the same arrangement as sync-docs.mjs and for the same reason. The
// library cannot move into web/, because library/ is linked from the README,
// browsed on GitHub, and regenerated by a Python script that knows that path.
// Copying it by hand would mean two sets of meshes drifting apart. So the
// copy under web/public/ is a build artifact: wiped and rebuilt by the
// predev/prebuild hooks, and gitignored.
//
// Everything is served from the site rather than linked to raw.githubusercontent
// so that a fork, a local preview, and an archived copy all work unchanged. The
// whole library is about 9 MB, which is under 1% of the GitHub Pages limit.
//
// The pages themselves do not fetch index.json: they read library/index.json
// directly at build time and render the result into static HTML, so filtering
// and detail pages work with JavaScript off. The copy served at
// /library/index.json is for anything outside this site that wants the catalogue
// as data, which is what the phase 3 customizer will need.

import { cpSync, existsSync, mkdirSync, readdirSync, rmSync, statSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const WEB = dirname(fileURLToPath(import.meta.url));
const LIB = join(WEB, '..', 'library');
const OUT = join(WEB, 'public', 'library');

if (!existsSync(join(LIB, 'index.json'))) {
	// A checkout always has this, because it is committed. Missing it means
	// something deleted the library, and a silent empty browser would be worse
	// than a failed build.
	console.error(
		'sync-library: library/index.json is missing. ' +
			'Run: python scripts/build_library.py',
	);
	process.exit(1);
}

rmSync(OUT, { recursive: true, force: true });
mkdirSync(OUT, { recursive: true });

// README.md is the GitHub-facing index. The site has its own browser at
// /library/, so shipping the Markdown table too would be a second, worse copy.
cpSync(LIB, OUT, { recursive: true, filter: (src) => !src.endsWith('README.md') });

let files = 0;
let bytes = 0;
function measure(dir) {
	for (const entry of readdirSync(dir, { withFileTypes: true })) {
		const path = join(dir, entry.name);
		if (entry.isDirectory()) measure(path);
		else {
			files += 1;
			bytes += statSync(path).size;
		}
	}
}
measure(OUT);

console.log(
	`sync-library: ${files} files, ${(bytes / 1024 / 1024).toFixed(1)} MB into public/library/`,
);
